/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unicesumar.ads.prog2.ae2;

import unicesumar.ads.prog2.ae2.q02.Q02;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        Q02.main(args);
    }
}
